db:
  driverClass: org.postgresql.Driver
  prod:
    url: jdbc:postgresql://172.31.254.84:5432/dbsmartbuildings
    user: postgres
    pass: Grp1SmartBuildTeam
  dev:
    url: jdbc:postgresql://localhost:5432/db-test
    user: postgres
    pass: Aqwzsxedc-123

sql:
  users :
    selectAll: SELECT * FROM users WHERE company_id = ? ORDER BY userid
    insert: INSERT INTO users(user_uid, name, company_id) values(?, ?, ?)
  cards:
    selectAll: SELECT * FROM cards c JOIN users u on u.userId = c.userId and u.company_id = ? ORDER BY cardid
    read: SELECT * FROM cards c JOIN users u on u.userId = c.userId WHERE cardid = ? ORDER BY cardid
socket:
  port: 63205
  

